/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Nestor Marchizone
 */
public class VistaMaterias extends javax.swing.JInternalFrame {
private java.util.HashSet<Materia> materias;
    /**
     * Creates new form VistaMaterias
     */
    public VistaMaterias(java.util.HashSet<Materia> materias) {
        initComponents();
        this.materias = materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLcodigoMateria = new javax.swing.JLabel();
        jLNombreMateria = new javax.swing.JLabel();
        jTNombreMateria = new javax.swing.JTextField();
        jLanio = new javax.swing.JLabel();
        jTanio = new javax.swing.JTextField();
        jBGuardarMat = new javax.swing.JButton();
        jBborrarMat = new javax.swing.JButton();
        jBsalirMat = new javax.swing.JButton();
        jTId_Materia = new javax.swing.JTextField();

        setTitle("Visualizacion Materias");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLcodigoMateria.setText("Codigo de la Materia");

        jLNombreMateria.setText("Nombre de la Materia");

        jLanio.setText("Año al que pertenece");

        jBGuardarMat.setText("Guardar");
        jBGuardarMat.addActionListener(this::jBGuardarMatActionPerformed);

        jBborrarMat.setText("Borrar");
        jBborrarMat.addActionListener(this::jBborrarMatActionPerformed);

        jBsalirMat.setText("Salir");
        jBsalirMat.addActionListener(this::jBsalirMatActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jBGuardarMat)
                        .addGap(66, 66, 66)
                        .addComponent(jBborrarMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jBsalirMat, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLNombreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLcodigoMateria, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTNombreMateria)
                            .addComponent(jTanio, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jTId_Materia))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcodigoMateria)
                    .addComponent(jTId_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreMateria)
                    .addComponent(jTNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLanio)
                    .addComponent(jTanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardarMat)
                    .addComponent(jBborrarMat)
                    .addComponent(jBsalirMat))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarMatActionPerformed
        try {
    int idMateria = Integer.parseInt(jTId_Materia.getText().trim());
    String nombre = jTNombreMateria.getText().trim();
    int anio = Integer.parseInt(jTanio.getText().trim());

    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Complete el nombre de la materia.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    Materia nueva = new Materia(idMateria, nombre, anio);
    if (!materias.add(nueva)) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Ya existe una materia con ese código.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Materia guardada correctamente.");
    jTId_Materia.setText("");
    jTNombreMateria.setText("");
    jTanio.setText("");

} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Código y año deben ser numéricos.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jBGuardarMatActionPerformed

    private void jBborrarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarMatActionPerformed
        try {
    int idMateria = Integer.parseInt(jTId_Materia.getText().trim());

    Materia aBorrar = null;
    for (Materia m : materias) {
        if (m.getIdMateria() == idMateria) {
            aBorrar = m;
            break;
        }
    }

    if (aBorrar == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No existe ninguna materia con ese código.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    materias.remove(aBorrar);
    javax.swing.JOptionPane.showMessageDialog(this, "Materia eliminada correctamente.");

    jTId_Materia.setText("");
    jTNombreMateria.setText("");
    jTanio.setText("");

} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese el código de la materia a borrar.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jBborrarMatActionPerformed

    private void jBsalirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirMatActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardarMat;
    private javax.swing.JButton jBborrarMat;
    private javax.swing.JButton jBsalirMat;
    private javax.swing.JLabel jLNombreMateria;
    private javax.swing.JLabel jLanio;
    private javax.swing.JLabel jLcodigoMateria;
    private javax.swing.JTextField jTId_Materia;
    private javax.swing.JTextField jTNombreMateria;
    private javax.swing.JTextField jTanio;
    // End of variables declaration//GEN-END:variables
}
