/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nestor Marchizone
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());
    static java.util.HashSet<Alumno> alumnos = new java.util.HashSet<>();
    static java.util.HashSet<Materia> materias = new java.util.HashSet<>();

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMenuItemNuevoAlumno = new javax.swing.JMenuItem();
        jMenuMateria = new javax.swing.JMenu();
        jMenuItemNuevaMateria = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemNuevoRegistro = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalirdelSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Alumnos");

        javax.swing.GroupLayout jDPaneEscritorioLayout = new javax.swing.GroupLayout(jDPaneEscritorio);
        jDPaneEscritorio.setLayout(jDPaneEscritorioLayout);
        jDPaneEscritorioLayout.setHorizontalGroup(
            jDPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jDPaneEscritorioLayout.setVerticalGroup(
            jDPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumno");

        jMenuItemNuevoAlumno.setText("Nuevo Alumno");
        jMenuItemNuevoAlumno.addActionListener(this::jMenuItemNuevoAlumnoActionPerformed);
        jMenuAlumno.add(jMenuItemNuevoAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenuMateria.setText("Materia");

        jMenuItemNuevaMateria.setText("Nueva Materia");
        jMenuItemNuevaMateria.addActionListener(this::jMenuItemNuevaMateriaActionPerformed);
        jMenuMateria.add(jMenuItemNuevaMateria);

        jMenuBar1.add(jMenuMateria);

        jMenuRegistro.setText("Registro");

        jMenuItemNuevoRegistro.setText("Nuevo Registro");
        jMenuItemNuevoRegistro.addActionListener(this::jMenuItemNuevoRegistroActionPerformed);
        jMenuRegistro.add(jMenuItemNuevoRegistro);

        jMenuBar1.add(jMenuRegistro);

        jMenuSalir.setText("Salir");

        jMenuItemSalirdelSistema.setText("Salir Del Sistema");
        jMenuItemSalirdelSistema.addActionListener(this::jMenuItemSalirdelSistemaActionPerformed);
        jMenuSalir.add(jMenuItemSalirdelSistema);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDPaneEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDPaneEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoAlumnoActionPerformed
        VistaAlumnos vista = new VistaAlumnos(alumnos);    
        jDPaneEscritorio.add(vista);
        vista.setVisible(true);
        try {
            vista.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
        }
    }//GEN-LAST:event_jMenuItemNuevoAlumnoActionPerformed

    private void jMenuItemNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaMateriaActionPerformed
        VistaMaterias vista = new VistaMaterias(materias);
        jDPaneEscritorio.add(vista);
        vista.setVisible(true);
        try {
            vista.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
        }
    }//GEN-LAST:event_jMenuItemNuevaMateriaActionPerformed

    private void jMenuItemSalirdelSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirdelSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirdelSistemaActionPerformed

    private void jMenuItemNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoRegistroActionPerformed
        VistaInscripcion vista = new VistaInscripcion(alumnos, materias);
        jDPaneEscritorio.add(vista);
        vista.setVisible(true);
        try {
            vista.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
        }
    }//GEN-LAST:event_jMenuItemNuevoRegistroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPaneEscritorio;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemNuevaMateria;
    private javax.swing.JMenuItem jMenuItemNuevoAlumno;
    private javax.swing.JMenuItem jMenuItemNuevoRegistro;
    private javax.swing.JMenuItem jMenuItemSalirdelSistema;
    private javax.swing.JMenu jMenuMateria;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
