/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 *
 */
public class VistaAlumnos extends javax.swing.JInternalFrame {
  private java.util.HashSet<Alumno> alumnos;
    /**
     * Creates new form VistaAlumnos
     */
   public VistaAlumnos(java.util.HashSet<Alumno> alumnos) {
        initComponents();
      this.alumnos = alumnos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLlegajo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLapellido = new javax.swing.JLabel();
        jTapellido = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jTlegajo = new javax.swing.JTextField();

        setTitle("Visualizacion Alumnos");

        jLlegajo.setText("Legajo");

        jLNombre.setText("Nombre");

        jLapellido.setText("Apellido");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(this::jBborrarActionPerformed);

        jBsalir.setText("Salir");
        jBsalir.addActionListener(this::jBsalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLlegajo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTlegajo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLapellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jBborrar)
                        .addGap(59, 59, 59)
                        .addComponent(jBsalir)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLlegajo)
                    .addComponent(jTlegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLapellido)
                    .addComponent(jTapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBborrar)
                    .addComponent(jBsalir))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
    int legajo = Integer.parseInt(jTlegajo.getText().trim());
    String apellido = jTapellido.getText().trim();
    String nombre = jTNombre.getText().trim();

    if (apellido.isEmpty() || nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Complete apellido y nombre.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    Alumno nuevo = new Alumno(legajo, apellido, nombre);
    if (!alumnos.add(nuevo)) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Ya existe un alumno con ese legajo.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    javax.swing.JOptionPane.showMessageDialog(this, "Alumno guardado correctamente.");
    jTlegajo.setText("");
    jTapellido.setText("");
    jTNombre.setText("");

} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "El legajo debe ser numérico.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        try {
    int legajo = Integer.parseInt(jTlegajo.getText().trim());

    Alumno aBorrar = null;
    for (Alumno a : alumnos) {
        if (a.getLegajo() == legajo) {
            aBorrar = a;
            break;
        }
    }

    if (aBorrar == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "No existe ningún alumno con ese legajo.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    alumnos.remove(aBorrar);
    javax.swing.JOptionPane.showMessageDialog(this,
            "Alumno eliminado correctamente.");

    jTlegajo.setText("");
    jTapellido.setText("");
    jTNombre.setText("");

} catch (NumberFormatException ex) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Ingrese el legajo del alumno a borrar.", "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jBborrarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLlegajo;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTapellido;
    private javax.swing.JTextField jTlegajo;
    // End of variables declaration//GEN-END:variables
}
