
public class VistaInscripcion extends javax.swing.JInternalFrame {

    private java.util.HashSet<Alumno> alumnos;
    private java.util.HashSet<Materia> materias;

    /**
     * Creates new form VistaInscripcion
     */
    public VistaInscripcion(java.util.HashSet<Alumno> alumnos, java.util.HashSet<Materia> materias) {
        initComponents();
        this.alumnos = alumnos;
        this.materias = materias;

        for (Materia m : materias) {
            jCSeleccionMateria.addItem(m.toString());
        }
        for (Alumno a : alumnos) {
            jCSeleccionAlumno.addItem(a.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSeleccionMateria = new javax.swing.JLabel();
        jLSeleccionAlumno = new javax.swing.JLabel();
        jCSeleccionMateria = new javax.swing.JComboBox<>();
        jCSeleccionAlumno = new javax.swing.JComboBox<>();
        jBInscribir = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setTitle("Inscripcion");

        jLSeleccionMateria.setText("Seleccione una Materia");

        jLSeleccionAlumno.setText("Seleccione un Alumno");

        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(this::jBInscribirActionPerformed);

        jBSalir.setText("Salir");
        jBSalir.addActionListener(this::jBSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSeleccionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBInscribir))
                    .addComponent(jLSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCSeleccionMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCSeleccionAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(jBSalir)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionMateria)
                    .addComponent(jCSeleccionMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSeleccionAlumno)
                    .addComponent(jCSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBSalir))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed
        String materiaTexto = (String) jCSeleccionMateria.getSelectedItem();
        String alumnoTexto = (String) jCSeleccionAlumno.getSelectedItem();

        Materia materiaSeleccionada = null;
        for (Materia m : materias) {
            if (m.toString().equals(materiaTexto)) {
                materiaSeleccionada = m;
                break;
            }
        }

        Alumno alumnoSeleccionado = null;
        for (Alumno a : alumnos) {
            if (a.toString().equals(alumnoTexto)) {
                alumnoSeleccionado = a;
                break;
            }
        }

        if (materiaSeleccionada == null || alumnoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe existir al menos un alumno y una materia cargados.",
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int antes = alumnoSeleccionado.cantidadMaterias();
        alumnoSeleccionado.agregarMateria(materiaSeleccionada);
        int despues = alumnoSeleccionado.cantidadMaterias();

        if (despues > antes) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    alumnoSeleccionado.getNombre() + " " + alumnoSeleccionado.getApellido()
                    + " fue inscripto en " + materiaSeleccionada.getNombre()
                    + ".\nTotal de materias: " + despues);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    alumnoSeleccionado.getNombre() + " " + alumnoSeleccionado.getApellido()
                    + " ya estaba inscripto en " + materiaSeleccionada.getNombre() + ".",
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBInscribirActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCSeleccionAlumno;
    private javax.swing.JComboBox<String> jCSeleccionMateria;
    private javax.swing.JLabel jLSeleccionAlumno;
    private javax.swing.JLabel jLSeleccionMateria;
    // End of variables declaration//GEN-END:variables
}
